package cs1302.arcade;

import java.util.Random;

import javafx.application.Application;
import javafx.application.Platform;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.shape.Rectangle;
import javafx.stage.Stage;
import javafx.event.EventHandler;
import javafx.scene.input.KeyEvent;
import javafx.scene.input.KeyCode;
import javafx.scene.input.MouseEvent;
import cs1302.arcade.welcomeScreen.*;
import cs1302.arcade.frogger.*;
import javafx.event.*;
import javafx.animation.*;
import javafx.util.*;
public class ArcadeApp extends Application {

    Group group = new Group();           // main container
    Random rng = new Random();           // random number generator
    Rectangle r = new Rectangle(20, 20); // some rectangle
    Scene s;
    WelcomeScreen newWelcome;
    LevelOneMap newLevel1;
    LevelTwoMap newLevel2;
    Timeline timelineW = new Timeline();
    Timeline timeline1 = new Timeline();
    Timeline timeline2 = new Timeline();
    Timeline timeline3 = new Timeline();
    
    /**
     * Return a mouse event handler that moves to the rectangle to a random
     * position any time a mouse event is generated by the associated node.
     * @return the mouse event handler
     */
    private EventHandler<? super MouseEvent> createMouseHandler() {
	return event -> {
	    System.out.println(event);
	    r.setX(rng.nextDouble() * (640 - r.getWidth()));
	    r.setY(rng.nextDouble() * (480 - r.getHeight()));
	};
    } // createMouseHandler

    /**
     * Return a key event handler that moves to the rectangle to the left
     * or the right depending on what key event is generated by the associated
     * node.
     * @return the key event handler
     */
    private EventHandler<? super KeyEvent> createKeyHandler() {
	return event -> {
	    System.out.println(event);
	    if (event.getCode() == KeyCode.LEFT)  r.setX(r.getX() - 10.0);
	    if (event.getCode() == KeyCode.RIGHT) r.setX(r.getX() + 10.0);
	    // TODO bounds checking
	};
    } // createKeyHandler

    /** {@inheritdoc} */
    @Override
    public void start(Stage stage) {
	
        /* You are allowed to rewrite this start method, add other methods,
         * files, classes, etc., as needed. This currently contains some
         * simple sample code for mouse and keyboard interactions with a node
         * (rectangle) in a group.
         

        r.setX(50);                                // 50px in the x direction (right)
        r.setY(50);                                // 50ps in the y direction (down)
        group.getChildren().add(r);                // add to main container
        r.setOnMouseClicked(createMouseHandler()); // clicks on the rectangle move it randomly
        group.setOnKeyPressed(createKeyHandler()); // left-right key presses move the rectangle
        Scene scene = new Scene(group, 640, 480);
        stage.setTitle("cs1302-arcade!");
        stage.setScene(scene);
        stage.sizeToScene();
        stage.show();

        // the group must request input focus to receive key events
        // @see https://docs.oracle.com/javase/8/javafx/api/javafx/scene/Node.html#requestFocus--
        group.requestFocus();
	*/

	/*/testing welcomeScreen
	WelcomeScreen newWelcome = new WelcomeScreen();
	newWelcome.setOnKeyPressed(newWelcome.createWelcomeKeyHandler());
	Scene scene = new Scene(newWelcome, 640, 520);
	//testing levelOne
	LevelOneMap newLevel1 = new LevelOneMap();
	newLevel1.setOnKeyPressed(newLevel1.getFrog().createKeyHandler());
	Scene scene2 = new Scene(newLevel1, 640, 520);
	LevelTwoMap newLevel2 = new LevelTwoMap(newLevel1);
	newLevel2.setOnKeyPressed(newLevel2.getFrog().createKeyHandler());
	Scene scene3 = new Scene(newLevel2, 640, 520);
	*/
	newWelcome = new WelcomeScreen();
	newWelcome.setOnKeyPressed(newWelcome.createWelcomeKeyHandler());
	newLevel1 = new LevelOneMap();
	newLevel1.setOnKeyPressed(newLevel1.getFrog().createKeyHandler());
	newLevel2 = new LevelTwoMap();
	newLevel2.setOnKeyPressed(newLevel2.getFrog().createKeyHandler());
	s = new Scene(newWelcome, 640, 520);
	setTimelineW();
	setTimeline1();
	setTimeline2();
	stage.setTitle("testing");
	stage.setScene(s);
	stage.sizeToScene();
	stage.show();
	newWelcome.requestFocus();
	newLevel1.requestFocus();
	newLevel2.requestFocus();
	checkForWelcomeScreen();		
    } // start

    public void checkForWelcomeScreen() {
	timelineW.play();
    }//checkForWelcomeScreen
    
    public void checkForWinsLosses1() {
	timeline1.play();
    }//checkForWins

    public void checkForWinsLosses2() {
	timeline2.play();
    }//checkForWins2

    public void setTimelineW() {
	EventHandler<ActionEvent> handler = event -> {
	    if(newWelcome.getSelect(1)) {
		newLevel1.resetStats();
		newLevel2.resetStats();
		s.setRoot(newLevel1);
		checkForWinsLosses1();
		timelineW.pause();
	    }
	};
	KeyFrame keyFrame = new KeyFrame(Duration.millis(1000/60), handler);
	timelineW.setCycleCount(Timeline.INDEFINITE);
	timelineW.getKeyFrames().add(0, keyFrame);
    }//setTimelineW

    public void setTimeline1() {
	EventHandler<ActionEvent> handler = event -> {
	    if(newLevel1.getWin()) {
		newLevel2.setStats(newLevel1);
		s.setRoot(newLevel2);
		checkForWinsLosses2();
		newLevel1.resetStats();
		timeline1.pause();
	    }
	    if(newLevel1.getLives() <= 0) {
		newWelcome.resetSelect();
		newLevel1.resetStats();
		s.setRoot(newWelcome);
		newWelcome.requestFocus();
		checkForWelcomeScreen();
		timeline1.pause();
	    }
	    if(newLevel1.getFrog().getQuit()) {
		newWelcome.resetSelect();
		newLevel1.resetStats();
		s.setRoot(newWelcome);
		newWelcome.requestFocus();
		checkForWelcomeScreen();
		timeline1.pause();
	    }
	};
	
	KeyFrame keyFrame = new KeyFrame(Duration.millis(1000/60), handler);
	timeline1.setCycleCount(Timeline.INDEFINITE);
	timeline1.getKeyFrames().add(keyFrame);
    }//setTimeline1

    public void setTimeline2() {
	EventHandler<ActionEvent> handler = event -> {
	    if(newLevel2.getWin()) {
		System.out.println("YOU WIN");//change to next level
	    }
	    if(newLevel2.getLives() <= 0) {
		newWelcome.resetSelect();
		newLevel1.resetStats();
		newLevel2.resetStats();
		s.setRoot(newWelcome);
		newWelcome.requestFocus();
		checkForWelcomeScreen();
		timeline2.pause();
	    }
	     if(newLevel2.getFrog().getQuit()) {
		newWelcome.resetSelect();
		newLevel2.resetStats();
		s.setRoot(newWelcome);
		newWelcome.requestFocus();
		checkForWelcomeScreen();
		timeline2.pause();
	    }
	};
	
	KeyFrame keyFrame = new KeyFrame(Duration.millis(1000/60), handler);
	timeline2.setCycleCount(Timeline.INDEFINITE);
	timeline2.getKeyFrames().add(keyFrame);
    }//setTimeline2
} // ArcadeApp
